---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: scorched-earth
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: letsencrypt-prod
spec:
  tls:
    - hosts:
        - scorched-earth.samarchyan.me
      secretName: scorched-earth-tls
  rules:
    - host: scorched-earth.samarchyan.me
      http:
        paths:
          - pathType: Prefix
            path: "/"
            backend:
              service:
                name: scorched-earth
                port:
                  number: 3001
