---
name: Deployment
on:
  push:
    branches:
      - main
  workflow_dispatch:
env:
  PROJECT: scorched-earth
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
      cancel-in-progress: true
    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2.0.0

      - name: Login to GitHub registry
        uses: docker/login-action@v2.0.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ github.token }}

      - name: Checkout code
        uses: actions/checkout@v4.2.2

      - name: Build and push docker image
        uses: docker/build-push-action@v3.1.1
        with:
          push: true
          tags: ghcr.io/${{ github.repository }}:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max
  restart_app:
    name: Restart app
    runs-on: ubuntu-latest
    needs: build
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
      cancel-in-progress: true
    steps:
      - name: Checkout code
        uses: actions/checkout@v3.0.2

      - name: Install kubectl
        uses: azure/setup-kubectl@v3.0

      - name: Configure kubectl
        run: |
          mkdir ~/.kube
          echo "$KUBECONFIG" > ~/.kube/config
        env:
          KUBECONFIG: ${{ secrets.KUBECONFIG }} # Done as a variable because it doesn't work in place.

      - name: Install doctl
        uses: digitalocean/action-doctl@v2.5.1
        with:
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
          version: "1.135.0"

      - name: Restart app
        run: |
          kubectl apply -f deployment/deployment.yaml
          kubectl apply -f deployment/ingress.yaml
          kubectl apply -f deployment/service.yaml
          kubectl rollout restart "deployment/$PROJECT"
          kubectl rollout status "deployment/$PROJECT"
